<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Storage Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Storage\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * ONE WRITABLE TARGET, THE PLACE EACH FILE IS IN, AND THE SWITCH BETWEEN THEM.
 *
 * The first tables this bundle has ever owned. It owned none for most of its
 * life and said so — the photo records stay in the modules that own them —
 * and what changed is that "which place do we write to" is a decision
 * somebody makes at a moment rather than a line in a config file.
 *
 * NOTHING IS BACKFILLED HERE AND THAT IS DELIBERATE. A row per existing file
 * would mean walking every module's records from a migration, which is a
 * migration reaching into schemas it does not own. {@see StorageLocator}
 * reads a file with no row as being in the CURRENT place, which is exactly
 * right for an installation that has only ever had one — and an installation
 * only ever has more than one after a switch, from which point every file is
 * recorded as it is written. The `files:locations:backfill` path, if one is
 * ever wanted for a huge existing installation, is a command and not this.
 */
final class Version20260921000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Storage targets: one writable place, the place each file is in, and the switch between them.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE storage_target (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                place_id VARCHAR(64) NOT NULL,
                role VARCHAR(16) NOT NULL,
                since TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_storage_target_place ON storage_target (place_id)');

        /*
         * ONE CURRENT AND ONE RETIRED, ENFORCED BY THE DATABASE. Two writable
         * targets would scatter files by accident of timing and no screen
         * could answer "where is it"; a partial unique index makes the state
         * unrepresentable rather than merely discouraged.
         */
        // Spelled the way PostgreSQL NORMALISES the predicate, which is what
        // schema introspection reads back: written any other way, every
        // installation's `migrations:diff` would offer to rebuild these two on
        // every run.
        $this->addSql("CREATE UNIQUE INDEX uniq_storage_target_current ON storage_target (role) WHERE ((role)::text = 'current'::text)");
        $this->addSql("CREATE UNIQUE INDEX uniq_storage_target_retired ON storage_target (role) WHERE ((role)::text = 'retired'::text)");

        $this->addSql(<<<'SQL'
            CREATE TABLE storage_file_location (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                file_key VARCHAR(512) NOT NULL,
                place_id VARCHAR(64) NOT NULL,
                byte_size BIGINT NOT NULL,
                recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_storage_file_location_key ON storage_file_location (file_key)');
        // The move asks "what is still in the old place" on every file it
        // carries, so that question gets an index rather than a scan.
        $this->addSql('CREATE INDEX idx_storage_file_location_place ON storage_file_location (place_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE storage_move (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                from_place_id VARCHAR(64) NOT NULL,
                to_place_id VARCHAR(64) NOT NULL,
                state VARCHAR(16) NOT NULL,
                total_files INT NOT NULL,
                total_bytes BIGINT NOT NULL,
                moved_files INT NOT NULL,
                moved_bytes BIGINT NOT NULL,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                progressed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_storage_move_state ON storage_move (state)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE storage_move');
        $this->addSql('DROP TABLE storage_file_location');
        $this->addSql('DROP TABLE storage_target');
    }
}
